name: SleepPotion
main: io.github.skepter.sleeppotion.Main
version: 1.4
description: Adds a potion of sleeping
author: Skepter
depend: [ProtocolLib]

commands:
  sleeppotion:
    description: Gives the target player a sleep potion